# Generated by Django 3.2 on 2022-04-06 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.CharField(max_length=255, verbose_name='Valor pago pelo cliente')),
                ('data_limpeza', models.DateField(verbose_name='Data da limpeza')),
                ('situacao', models.CharField(choices=[('1', 'Pendente'), ('2', 'Realizado'), ('3', 'Cancelado')], max_length=255, verbose_name='Situação do atendimento')),
            ],
            options={
                'db_table': 'atendimento',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('id_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atendimento')),
            ],
            options={
                'db_table': 'atendimento_servico',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=11)),
                ('localidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do serviço')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição breve do serviço')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor do serviço')),
                ('status', models.BooleanField(default=True, verbose_name='Status do serviço')),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.endereco')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
            ],
            options={
                'db_table': 'cliente',
            },
            bases=('core.endereco',),
        ),
        migrations.CreateModel(
            name='AtendimentoServicoEndereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('id_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atendimentoservico')),
                ('id_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
            ],
            options={
                'db_table': 'atendimento_servico_endereco',
            },
        ),
        migrations.AddField(
            model_name='atendimentoservico',
            name='id_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico'),
        ),
    ]
