# Generated by Django 3.2 on 2022-04-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
