# Generated by Django 3.2 on 2022-04-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_endereco_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='E-mail'),
        ),
    ]
