# Generated by Django 3.2 on 2022-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220407_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentoservicoendereco',
            name='id_atendimento',
        ),
        migrations.RemoveField(
            model_name='atendimentoservicoendereco',
            name='id_endereco',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='desconto',
            field=models.BooleanField(default=False, verbose_name='Desconto'),
        ),
        migrations.DeleteModel(
            name='AtendimentoServico',
        ),
        migrations.DeleteModel(
            name='AtendimentoServicoEndereco',
        ),
    ]
